language: python
python:
  - '3.6'
sudo: false
before_script:
  - pip install tox
script:
  - tox
notifications:
  email: false
  slack:
    secure: VjsVPx+qn7IRM3HMoYXkQkgk7FJrtBKPw/attKPxWCygOjLcTyN1Tot/ceT7hLJ5jMWt7tKJhPpg+CD+lAVRsRkdlXzzdnB8sYJXdTLl1X3N6P5yGOJA4uQpOLdnbjI4FekE17KlxfQK0NXfHjIJ5nsjNSYWsYEwo0SOn1wN807zKdSMX/Wx3hmWc9jRz1GZNyPlhSYilpsAtGvtf6dxbsTBBMvakEqG5V1PB/yh/1tHTnUGo7IvTPqeEMGxE+vuOsRy5EJ9pozmwRSr7s/lyO7HXFub0S7hnh4fXRegIhuqRkEP5LG/w8q/UKS6t/eZPQG3KwDaKJ/h1hxwCspId61OsJnBhhxRJVIqbHsrw4wbZxOMQN6a5j4yh3uWUmfrSkp82nm1jb1YWcXr1RMpJpqZsZ9wj+cM1PIuSRRZ4qCGTbRz840sijENU6jhJnwYqSp9pppeIUc+xmmgXH46CcCtdJyJHacZfdbk4SvPycsJCS/+dsNbhuccQDVUUOYtcxDc+J8kVn3nb+lZDnha2mr36pRen3+YhXYod53lzcuFU4VYmj8zhizpEKt/CkPFsZMoMlxHSoHj0xrldY4SQaOj5houbj5FzlwR/1UoHipfWlWlLvfPMYWlySta1v+WBOH6wPbZz7jgQnzZhLrKjA4IcKyLuTG7Uv9S6aapZkI=
