defaults: &defaults
  docker:
    - image: circleci/python:3.6

version: 2
jobs:
  # Testing job which builds a small model and runs sanity tests
  # against it.
  test:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user tox
      - run: python -m tox
      - persist_to_workspace:
          root: generate
          paths:
            - assets
      - run: tar -cvzf test-shapes.tar.gz test/shapes
      - store_artifacts:
          path: test-shapes.tar.gz
          destination: test-shapes.tar.gz

  # Running a job to build not-a-shapes.
  nas-gen:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: generate
      - run: pip install --user -r requirements-dev.txt
      - run: python generate/nas_gen.py
      - persist_to_workspace:
          root: generate
          paths:
            - shapes/nas

  # Parallel jobs to build each type of shape.
  circle-gen: &shape-job
    <<: *defaults
    environment:
      - SHAPE_TYPES: circle
    steps:
      - checkout
      - attach_workspace:
          at: generate
      - run: pip install --user -r requirements-dev.txt
      - run: python generate/shape_gen.py
      - persist_to_workspace:
          root: generate
          paths:
            - shapes/*
  cross-gen:
    <<: *shape-job
    environment:
      - SHAPE_TYPES: cross
  pentagon-gen:
    <<: *shape-job
    environment:
      - SHAPE_TYPES: pentagon
  quarter-circle-gen:
    <<: *shape-job
    environment:
      - SHAPE_TYPES: quarter-circle
  rectangle-gen:
    <<: *shape-job
    environment:
      - SHAPE_TYPES: rectangle
  semicircle-gen:
    <<: *shape-job
    environment:
      - SHAPE_TYPES: semicircle
  square-gen:
    <<: *shape-job
    environment:
      - SHAPE_TYPES: square
  star-gen:
    <<: *shape-job
    environment:
      - SHAPE_TYPES: star
  trapezoid-gen:
    <<: *shape-job
    environment:
      - SHAPE_TYPES: trapezoid
  triangle-gen:
    <<: *shape-job
    environment:
      - SHAPE_TYPES: triangle

  # Training job using the shapes from the shapes above.
  train:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: generate
      - run: pip install --user -r requirements-dev.txt
      - run: python generate/train.py
      - persist_to_workspace:
          root: target_finder_model
          paths:
            - data/*

  # Job that creates a tar archive for the python library.
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: target_finder_model
      - run: ./scripts/create-release.sh
      - store_artifacts:
          path: release
          destination: release
      - persist_to_workspace:
          root: '.'
          paths:
            - release

  # Job that publishes to GitHub Releases for tags.
  publish:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: '.'
      - run: |
          ghr \
            -t ${GITHUB_TOKEN} \
            -u ${CIRCLE_PROJECT_USERNAME} \
            -r ${CIRCLE_PROJECT_REPONAME} \
            -c ${CIRCLE_SHA1} \
            -delete \
            ${CIRCLE_TAG} \
            ./release/

workflows:
  version: 2
  test-generate-train:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - nas-gen: &gen-job
          requires:
            - test
          filters: &release-filters
            tags:
              only: /^v.*/
            branches:
              only: master
      - circle-gen:
          <<: *gen-job
      - cross-gen:
          <<: *gen-job
      - pentagon-gen:
          <<: *gen-job
      - quarter-circle-gen:
          <<: *gen-job
      - rectangle-gen:
          <<: *gen-job
      - semicircle-gen:
          <<: *gen-job
      - square-gen:
          <<: *gen-job
      - star-gen:
          <<: *gen-job
      - trapezoid-gen:
          <<: *gen-job
      - triangle-gen:
          <<: *gen-job
      - train:
          requires:
            - nas-gen
            - circle-gen
            - cross-gen
            - pentagon-gen
            - quarter-circle-gen
            - rectangle-gen
            - semicircle-gen
            - square-gen
            - star-gen
            - trapezoid-gen
            - triangle-gen
          filters:
            <<: *release-filters
      - release:
          requires:
            - train
          filters:
            <<: *release-filters
      - publish:
          requires:
            - release
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
